# @author Alejandro Galue <agalue@opennms.org>
#
# Requires the ingress-dns add-on in Minikube, and some configuration in your host machine

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: onms-ingress
  namespace: opennms
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
spec:
  tls:
    - secretName: opennms-ingress-cert
      hosts:
        - onms.test
        - grafana.test
        - kafka-manager.test
        - kibana.test
        - tracing.test
  rules:
    - host: onms.test
      http:
        paths:
          - path: /
            backend:
              serviceName: opennms-core
              servicePort: 8980
    - host: grafana.test
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
    - host: kafka-manager.test
      http:
        paths:
          - path: /
            backend:
              serviceName: kafka-manager
              servicePort: 9000
    - host: kibana.test
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana
              servicePort: 5601
    - host: tracing.test
      http:
        paths:
          - path: /
            backend:
              serviceName: onms-tracing-query
              servicePort: 16686

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grpc-ingress
  namespace: opennms
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
spec:
  tls:
    - secretName: grpc-ingress-cert
      hosts:
        - grpc.test
  rules:
    - host: grpc.test
      http:
        paths:
          - path: /
            backend:
              serviceName: grpc-server
              servicePort: 8990
