# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: onms-ingress
  namespace: opennms
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
spec:
  tls:
    - secretName: opennms-ingress-cert
      hosts:
        - onms.minikube.local
        - grafana.minikube.local
        - kafka-manager.minikube.local
        - kibana.minikube.local
        - tracing.minikube.local
  rules:
    - host: onms.minikube.local
      http:
        paths:
          - path: /
            backend:
              serviceName: opennms-core
              servicePort: 8980
    - host: grafana.minikube.local
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
    - host: kafka-manager.minikube.local
      http:
        paths:
          - path: /
            backend:
              serviceName: kafka-manager
              servicePort: 9000
    - host: kibana.minikube.local
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana
              servicePort: 5601
    - host: tracing.minikube.local
      http:
        paths:
          - path: /
            backend:
              serviceName: onms-tracing-query
              servicePort: 16686

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grpc-ingress
  namespace: opennms
  annotations:
    cert-manager.io/issuer: selfsigned-issuer
spec:
  tls:
    - secretName: grpc-ingress-cert
      hosts:
        - grpc.minikube.local
  rules:
    - host: grpc.minikube.local
      http:
        paths:
          - path: /
            backend:
              serviceName: grpc-server
              servicePort: 8990
