# @author Alejandro Galue <agalue@opennms.org>

---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: cassandra-reaper
  namespace: opennms

---
$patch: delete
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-reaper
  namespace: opennms
