# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esmaster
  namespace: opennms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: esmaster
        env:
        - name: xpack.security.enabled
          $patch: delete
        - name: discovery.seed_hosts
          value: esmaster.opennms.svc.cluster.local
        - name: cluster.initial_master_nodes
          value: esmaster-0
        - name: bootstrap.memory_lock
          value: 'false'
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
          $patch: replace
