# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: alec
  namespace: opennms
spec:
  template:
    spec:
      affinity:
        $patch: delete
      containers:
      - name: alec
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
          $patch: replace
