# @author Alejandro Galue <agalue@opennms.org>
# GCE doesn't support K8s 1.19 in the stable channel (2021-04-01)

---
$patch: delete
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onms-ingress
  namespace: opennms

---
$patch: delete
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grpc-ingress
  namespace: opennms
