# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: onms-ingress
  namespace: opennms
spec:
  tls:
    - secretName: opennms-ingress-cert
      hosts:
        - onms.gce.agalue.net
        - grafana.gce.agalue.net
        - kafka-manager.gce.agalue.net
        - tracing.gce.agalue.net
        - grpc.gce.agalue.net
  rules:
    - host: onms.gce.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: opennms-core
              servicePort: 8980
    - host: grafana.gce.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
    - host: kafka-manager.gce.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: kafka-manager
              servicePort: 9000
    - host: tracing.gce.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: onms-tracing-query
              servicePort: 16686

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grpc-ingress
  namespace: opennms
spec:
  tls:
    - secretName: grpc-ingress-cert
      hosts:
        - grpc.gce.agalue.net
  rules:
    - host: grpc.gce.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: grpc-server
              servicePort: 8990
