# @author Alejandro Galue <agalue@opennms.org>

---
$patch: delete
apiVersion: v1
kind: Service
metadata:
  name: esmaster
  namespace: opennms

---
$patch: delete
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esmaster
  namespace: opennms
