# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minion
  namespace: opennms
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: minion
        resources:
          limits:
            memory: 1Gi
            cpu: 250m
          requests:
            memory: 512Mi
            cpu: 100m
