# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sentinel
  namespace: opennms
spec:
  maxReplicas: 1
  minReplicas: 1

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel
  namespace: opennms
spec:
  replicas: 1
  template:
    spec:
      affinity:
        $patch: delete
      containers:
      - name: sentinel
        resources:
          limits:
            memory: 1Gi
            cpu: 250m
          requests:
            memory: 512Mi
            cpu: 100m
