# @author Alejandro Galue <agalue@opennms.org>
#
# FOR TESTING/DEVELOPMENT ONLY
#
# WARNING:
# - The cassandra user (uid: 999, gid: 999) cannot be used in OpenShift by default.
# - Make sure to take appropriate actions when stopping or decomissioning (shrink cluster).
# - Cassandra expects to have very fast disks for the PVC to avoid performance issues.
# - Cassandra doesn't expect changes on IP addresses, and Kubernetes doesn't guarrantee that.
#
# TODO:
# - Check if it is possible to use replace_address_first_boot on subsequent boots.
#
# For production, take a look at the existing operators; which deal with all the limittions.
# For instance, https://k8ssandra.io/

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
  namespace: opennms
  labels:
    app: cassandra
data:
  ready-probe.sh: |+
    #!/usr/bin/bash
    if [[ $(nodetool -u cassandra -pw cassandra status | grep $CASSANDRA_LISTEN_ADDRESS) == *"UN"* ]]; then
      if [[ $DEBUG ]]; then
        echo "UN";
      fi
      exit 0;
    else
      if [[ $DEBUG ]]; then
        echo "Not Up";
      fi
      exit 1;
    fi
  # Be able to access Cassandra through JMX (for cassandra-reaper and for monitoring purposes)
  jmxremote.password: |+
    monitorRole QED
    controlRole R&D
    cassandra cassandra
  # For Cassandra 3.11.x
  # Enable G1GC as the performance tests on the field have proven good results.
  jvm.options: |+
    -ea
    -XX:+UseThreadPriorities
    -XX:ThreadPriorityPolicy=42
    -XX:+HeapDumpOnOutOfMemoryError
    -Xss256k
    -XX:StringTableSize=1000003
    -XX:+AlwaysPreTouch
    -XX:-UseBiasedLocking
    -XX:+UseTLAB
    -XX:+ResizeTLAB
    -XX:+UseNUMA
    -XX:+PerfDisableSharedMem
    -Djava.net.preferIPv4Stack=true
    -XX:+UseG1GC
    -XX:G1RSetUpdatingPauseTimePercent=5
    -XX:MaxGCPauseMillis=500
    -XX:+PrintGCDetails
    -XX:+PrintGCDateStamps
    -XX:+PrintHeapAtGC
    -XX:+PrintTenuringDistribution
    -XX:+PrintGCApplicationStoppedTime
    -XX:+PrintPromotionFailure
    -XX:+UseGCLogFileRotation
    -XX:NumberOfGCLogFiles=10
    -XX:GCLogFileSize=10M
  # For Cassandra 4.x
  # Enable G1GC (default in JDK 11) as the performance tests on the field have proven good results.
  jvm11-server.options: |+
    -XX:+UseG1GC
    -XX:G1RSetUpdatingPauseTimePercent=5
    -XX:MaxGCPauseMillis=500
    -Djdk.attach.allowAttachSelf=true
    --add-exports java.base/jdk.internal.misc=ALL-UNNAMED
    --add-exports java.base/jdk.internal.ref=ALL-UNNAMED
    --add-exports java.base/sun.nio.ch=ALL-UNNAMED
    --add-exports java.management.rmi/com.sun.jmx.remote.internal.rmi=ALL-UNNAMED
    --add-exports java.rmi/sun.rmi.registry=ALL-UNNAMED
    --add-exports java.rmi/sun.rmi.server=ALL-UNNAMED
    --add-exports java.sql/java.sql=ALL-UNNAMED
    --add-opens java.base/java.lang.module=ALL-UNNAMED
    --add-opens java.base/jdk.internal.loader=ALL-UNNAMED
    --add-opens java.base/jdk.internal.ref=ALL-UNNAMED
    --add-opens java.base/jdk.internal.reflect=ALL-UNNAMED
    --add-opens java.base/jdk.internal.math=ALL-UNNAMED
    --add-opens java.base/jdk.internal.module=ALL-UNNAMED
    --add-opens java.base/jdk.internal.util.jar=ALL-UNNAMED
    --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: opennms
  labels:
    app: cassandra
spec:
  clusterIP: None
  ports:
  - port: 7000
    name: intra-node
  - port: 7001
    name: tls-intra-node
  - port: 7199
    name: jmx
  - port: 9042
    name: cql
  selector:
    app: cassandra

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: opennms
  labels:
    app: cassandra
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 1800
      securityContext: # In order to be able to write data as non-root on the volumes
        fsGroup: 999 # Default cassandra user
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: cassandra
        image: cassandra:3.11 # Use either 3.11 or 4.0
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: common-settings
        - name: LOCAL_JMX
          value: no
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: MAX_HEAP_SIZE
          value: $(MEM_TOTAL_MB)m
        - name: HEAP_NEWSIZE
          value: $(MEM_TOTAL_MB)m
        - name: CASSANDRA_SEEDS
          value: cassandra-0.cassandra.opennms.svc.cluster.local
        - name: CASSANDRA_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_CLUSTER_NAME
              name: common-settings
        # The following 3 variables are required to use NetworkTopologyStrategy with the Newts keyspace
        - name: CASSANDRA_ENDPOINT_SNITCH
          value: GossipingPropertyFileSnitch
        - name: CASSANDRA_DC
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_DC
              name: common-settings
        - name: CASSANDRA_RACK
          valueFrom:
            fieldRef:
              fieldPath: metadata.name # TODO spec.nodeName seems more accurate, but an affinity policy might be better.
        - name: CASSANDRA_LISTEN_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        volumeMounts:
        - name: data
          mountPath: /cassandra_data
        - name: cassandra-config
          mountPath: /ready-probe.sh
          subPath: ready-probe.sh
        - name: cassandra-config
          mountPath: /etc/cassandra/jmxremote.password
          subPath: jmxremote.password
        - name: cassandra-config # For Cassandra 4.x
          mountPath: /etc/cassandra/jvm11-server.options
          subPath: jvm11-server.options
        - name: cassandra-config # For Cassandra 3.11.x
          mountPath: /etc/cassandra/jvm.options
          subPath: jvm.options
        lifecycle:
          preStop:
            exec:
              command:
              - nodetool -u cassandra -pw cassandra drain
        resources:
          limits:
            cpu: 4
            memory: 4Gi
          requests:
            cpu: 2
            memory: 2Gi
        securityContext:
          runAsUser: 999
          capabilities:
            add:
            - IPC_LOCK
        readinessProbe:
          exec:
            command:
            - bash
            - /ready-probe.sh
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          tcpSocket:
            port: cql
          initialDelaySeconds: 90
          periodSeconds: 60
      volumes:
      - name: cassandra-config
        configMap:
          name: cassandra-config
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi
