# @author Alejandro Galue <agalue@opennms.org>
#
# This is an optional component
#
# http://cassandra-reaper.io/docs/configuration/docker_vars/
# Main UI: https://cassandra-reaper.$YOUR_DOMAIN/webui/

---
apiVersion: v1
kind: Service
metadata:
  name: cassandra-reaper
  namespace: opennms
  labels:
    app: cassandra-reaper
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: http
  - port: 8081
    name: http-admin
  selector:
    app: cassandra-reaper

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-reaper
  namespace: opennms
  labels:
    app: cassandra-reaper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-reaper
  template:
    metadata:
      labels:
        app: cassandra-reaper
    spec:
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: cassandra.opennms.svc.cluster.local:9042
        - name: TIMEOUT
          value: '900'
      - name: init-database
        image: cassandra:3.11
        imagePullPolicy: IfNotPresent
        command: [ sh, -c, 'cqlsh -e "$CQL" $CASSANDRA_HOST' ]
        env:
        - name: CASSANDRA_HOST
          value: cassandra.opennms.svc.cluster.local
        - name: REP_FACTOR
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_REPLICATION_FACTOR
              name: common-settings
        - name: CQL
          value: "CREATE KEYSPACE IF NOT EXISTS reaper_db WITH replication = {'class' : 'NetworkTopologyStrategy', 'Main' : $(REP_FACTOR) };"
      containers:
      - name: cassandra-reaper
        image: thelastpickle/cassandra-reaper:1.4.8
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: common-settings
        - name: REAPER_STORAGE_TYPE
          value: cassandra
        - name: REAPER_CASS_CONTACT_POINTS
          value: "[ cassandra.opennms.svc.cluster.local ]"
        - name: REAPER_CASS_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: CASSANDRA_CLUSTER_NAME
              name: common-settings
        - name: REAPER_JMX_AUTH_USERNAME # See ConfigMap/cassandra-config from cassandra.yaml
          value: cassandra
        - name: REAPER_JMX_AUTH_PASSWORD # See ConfigMap/cassandra-config from cassandra.yaml
          value: cassandra
        - name: REAPER_CASS_KEYSPACE # See initContainers:init-database
          value: reaper_db
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 8081
          name: http-admin
        resources:
          limits:
            cpu: 200m
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 512Mi
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
