# @author Alejandro Galue <agalue@opennms.org>
#
# WARNING:
# - The elasticsearch user (uid: 1000, gid: 1000) cannot be used in OpenShift by default.

---
apiVersion: v1
kind: Service
metadata:
  name: esmaster
  namespace: opennms
  labels:
    app: elasticsearch
    deployment: drift
    role: esmaster
spec:
  clusterIP: None
  ports:
  - port: 9200
    name: http
  - port: 9300
    name: transport
  selector:
    role: esmaster

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esmaster
  namespace: opennms
  labels:
    app: elasticsearch
    deployment: drift
    role: esmaster
spec:
  serviceName: esmaster
  replicas: 3 # The solution is designed for 3 masters only
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      role: esmaster
  template:
    metadata:
      labels:
        app: elasticsearch
        deployment: drift
        role: esmaster
    spec:
      terminationGracePeriodSeconds: 300
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-sysctl
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: esmaster
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsUser: 1000
          capabilities:
            add:
            - IPC_LOCK
            - SYS_RESOURCE
        ports:
        - containerPort: 9200
          name: http
        - containerPort: 9300
          name: transport
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: common-settings
        - name: cluster.name
          value: OpenNMS
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: xpack.security.enabled
          value: 'false' # Enabling security requires a license
        - name: discovery.zen.ping.unicast.hosts
          value: esmaster.opennms.svc.cluster.local
        - name: discovery.zen.minimum_master_nodes
          value: '2' # Requires a minimum of 3 replicas
        - name: node.master
          value: 'true'
        - name: node.data
          value: 'false'
        - name: node.ingest
          value: 'false'
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: ES_JAVA_OPTS # TODO jvm.options default will be used if Xms/Xmx are not passed
          value: -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ELASTICSEARCH_PASSWORD
              name: onms-passwords
        volumeMounts:
        - name: es-data
          mountPath: /usr/share/elasticsearch/data
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 30
          periodSeconds: 15
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 60
          periodSeconds: 60
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi

