# @author Alejandro Galue <agalue@opennms.org>
# Source: https://github.com/OpenNMS/opennms-drift-kubernetes/tree/master/tools/event-watcher
#
# A simple K8s Controller that generate OpenNMS events upon reception of certain K8s events.
# The event watcher requires a service account with cluster-level access to get, list, and watch pods, services, and events.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-watcher-user
  namespace: opennms

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-watcher-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - events
  verbs:
  - get
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-watcher-binding
subjects:
  - kind: ServiceAccount
    name: event-watcher-user
    namespace: opennms
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: event-watcher-role

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-watcher
  namespace: opennms
spec:
  replicas: 1 # Do not scale
  selector:
    matchLabels:
      app: event-watcher
  template:
    metadata:
      labels:
        app: event-watcher
    spec:
      serviceAccountName: event-watcher-user
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: opennms-core.opennms.svc.cluster.local:8980
        - name: TIMEOUT
          value: '900'
      containers:
      - name: event-watcher
        image: agalue/onms-k8s-watcher-go:latest
        imagePullPolicy: Always
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: common-settings
        - name: ONMS_URL
          value: http://opennms-core.opennms.svc.cluster.local:8980/opennms
        - name: ONMS_USER
          value: admin
        - name: ONMS_PASSWD
          valueFrom:
            secretKeyRef:
              key: OPENNMS_UI_ADMIN_PASSWORD
              name: onms-passwords
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
