# @author Alejandro Galue <agalue@opennms.org>
#
# With Kops, the dns-controller will automatically create entries on Route53 when --watch-ingress=true is applied.
# With EKS, GKE and AKS, external-dns will create entries on Route53.
#
# WARNING:
# Please use your own domains. This is not intended to be used by any user.

# For testing purposes only (minikube)
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: opennms
spec:
  selfSigned: {}

# For cloud providers / public access
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: opennms
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: agalue@opennms.org
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx

# Access to applications based on HTTP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: onms-ingress
  namespace: opennms
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-name: route
    ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    cert-manager.io/issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: 'true'
spec:
  tls:
    - secretName: opennms-ingress-cert
      hosts:
        - onms.aws.agalue.net
        - onmsui.aws.agalue.net
        - cassandra-reaper.aws.agalue.net
        - grafana.aws.agalue.net
        - hasura.aws.agalue.net
        - kibana.aws.agalue.net
        - elastichq.aws.agalue.net
        - kafka-manager.aws.agalue.net
        - tracing.aws.agalue.net
  rules:
    - host: onms.aws.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: opennms-core
              servicePort: 8980
    - host: cassandra-reaper.aws.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: cassandra-reaper
              servicePort: 8080
    - host: grafana.aws.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
    - host: hasura.aws.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: hasura
              servicePort: 8080
    - host: kafka-manager.aws.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: kafka-manager
              servicePort: 9000
    - host: kibana.aws.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana
              servicePort: 5601
    - host: elastichq.aws.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: elastichq
              servicePort: 5000
    - host: onmsui.aws.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: opennms-ui
              servicePort: 8980
          - path: /opennms/nrt
            backend:
              serviceName: opennms-core
              servicePort: 8980
    - host: tracing.aws.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: onms-tracing-query
              servicePort: 16686

# Access to applications based on gRPC
# TODO: Currently not working, although the gRPC server works as expected.

# Enable client certificate authentication
# nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
#
# Create the secret containing the trusted ca certificates
# nginx.ingress.kubernetes.io/auth-tls-secret: "default/ca-secret"
#
# Specify the verification depth in the client certificates chain
# nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
#
# Specify an error page to be redirected to verification errors
# nginx.ingress.kubernetes.io/auth-tls-error-page: "http://www.mysite.com/error-cert.html"
#
# Specify if certificates are passed to upstream server
# nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: grpc-ingress
  namespace: opennms
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
spec:
  tls:
    - secretName: grpc-ingress-cert
      hosts:
        - grpc.aws.agalue.net
  rules:
    - host: grpc.aws.agalue.net
      http:
        paths:
          - path: /
            backend:
              serviceName: grpc-server
              servicePort: 8990
