# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: opennms
  labels:
    app: grafana
    deployment: drift
spec:
  ports:
  - port: 3000
  selector:
    app: grafana

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: opennms
  labels:
    app: grafana
    deployment: drift
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
        deployment: drift
    spec:
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: postgresql.opennms.svc.cluster.local:5432
        - name: TIMEOUT
          value: '600'
      - name: init-database
        image: postgres:11-alpine
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - /bin/grafana-init.sh
        env:
        - name: PGHOST
          value: postgresql.opennms.svc.cluster.local
        - name: PGPORT
          value: '5432'
        - name: PGUSER
          value: postgres
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: onms-passwords
        - name: GF_DATABASE_NAME
          value: grafana
        - name: GF_DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: GRAFANA_DB_USERNAME
              name: onms-passwords
        - name: GF_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: GRAFANA_DB_PASSWORD
              name: onms-passwords
        volumeMounts:
        - name: opennms-config
          mountPath: /bin/grafana-init.sh
          subPath: grafana-init.sh
      containers:
      - name: grafana-helm
        image: opennms/helm:3.0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: common-settings
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: GRAFANA_UI_ADMIN_PASSWORD
              name: onms-passwords
        - name: GF_DATABASE_TYPE
          value: postgres
        - name: GF_DATABASE_HOST
          value: postgresql.opennms.svc.cluster.local:5432
        - name: GF_DATABASE_NAME
          value: grafana
        - name: GF_DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: GRAFANA_DB_USERNAME
              name: onms-passwords
        - name: GF_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: GRAFANA_DB_PASSWORD
              name: onms-passwords
        - name: GF_SESSION_PROVIDER
          value: postgres
        - name: GF_SESSION_PROVIDER_CONFIG
          value: dbname=$(GF_DATABASE_NAME) user=$(GF_DATABASE_USER) password=$(GF_DATABASE_PASSWORD) host=postgresql.opennms.svc.cluster.local port=5432 sslmode=disable
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60
      volumes:
      - name: opennms-config
        configMap:
          name: opennms-config
