# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: opennms
  labels:
    app: grpc-server
spec:
  ports:
  - port: 8990
    name: http
  selector:
    app: grpc-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: opennms
  labels:
    app: grpc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: kafka.opennms.svc.cluster.local:9092
        - name: TIMEOUT
          value: '600'
      containers:
      - name: grpc-server
        image: agalue/grpc-server:H26
        imagePullPolicy: Always
        ports:
        - containerPort: 8990
          name: http
        env:
        - name: BOOTSTRAP_SERVERS
          value: kafka.opennms.svc.cluster.local:9092
        - name: TLS_ENABLED
          value: 'false'
        - name: INSTANCE_ID
          valueFrom:
            configMapKeyRef:
              key: OPENNMS_INSTANCE_ID
              name: common-settings
        - name: CONSUMER_AUTO_OFFSET_RESET
          value: latest
        - name: CONSUMER_MAX_PARTITION_FETCH_BYTES
          value: '5000000'
        - name: PRODUCER_MAX_REQUEST_SIZE
          value: '5000000'
        - name: MAX_MESSAGE_SIZE
          value: '4194304'
        - name: MEM_TOTAL_MB
          valueFrom:
            resourceFieldRef:
              resource: requests.memory
              divisor: 1Mi
        - name: JAVA_OPTS # Preferred way instead of opennms.conf
          value: -Xms$(MEM_TOTAL_MB)m -Xmx$(MEM_TOTAL_MB)m
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        readinessProbe:
          exec:
            command: ['/bin/grpc_health_probe', '-addr', ':8990', '-rpc-timeout', '2s']
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          exec:
            command: ['/bin/grpc_health_probe', '-addr', ':8990', '-rpc-timeout', '2s']
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 3

