# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  namespace: opennms
  labels:
    app: kafka-manager
spec:
  ports:
  - port: 9000
  selector:
    app: kafka-manager

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: opennms
  labels:
    app: kafka-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      initContainers:
      - name: dependencies
        image: waisbrot/wait
        imagePullPolicy: IfNotPresent
        env:
        - name: TARGETS
          value: kafka.opennms.svc.cluster.local:9092
        - name: TIMEOUT
          value: '600'
      containers:
      - name: kafka-manager
        image: hlebalbau/kafka-manager:stable
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TIMEZONE
              name: common-settings
        - name: ZK_HOSTS
          value: zookeeper.opennms.svc.cluster.local:2181
        - name: KAFKA_MANAGER_AUTH_ENABLED
          value: 'true'
        - name: KAFKA_MANAGER_USERNAME
          valueFrom:
            secretKeyRef:
              key: KAFKA_MANAGER_USERNAME
              name: onms-passwords
        - name: KAFKA_MANAGER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: KAFKA_MANAGER_PASSWORD
              name: onms-passwords
        - name: APPLICATION_SECRET
          valueFrom:
            secretKeyRef:
              key: KAFKA_MANAGER_APPLICATION_SECRET
              name: onms-passwords
        ports:
        - containerPort: 9000
          name: http
        resources:
          limits:
            memory: 512Mi
            cpu: 200m
          requests:
            memory: 256Mi
            cpu: 100m
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60