# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtrigger-kafka
  labels:
    svc: mqtrigger
    messagequeue: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      svc: mqtrigger
      messagequeue: kafka
  template:
    metadata:
      labels:
        svc: mqtrigger
        messagequeue: kafka
    spec:
      containers:
      - name: mqtrigger
        image: "index.docker.io/fission/fission-bundle"
        imagePullPolicy: IfNotPresent
        command: ["/fission-bundle"]
        args: ["--mqt", "--routerUrl", "http://router.fission", "--collectorEndpoint", ""]
        env:
        - name: MESSAGE_QUEUE_TYPE
          value: kafka
        - name: MESSAGE_QUEUE_URL
          value: "kafka.opennms.svc.cluster.local:9092"
        - name: MESSAGE_QUEUE_KAFKA_VERSION
          value: "2.5.0"
      serviceAccount: fission-svc

