# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: slack-forwarder
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: agalue/slack-forwarder
        imagePullPolicy: Always
        env:
        - name: SLACK_URL
          valueFrom:
            secretKeyRef:
              key: SLACK_URL
              name: serverless-config
        - name: ONMS_URL
          valueFrom:
            secretKeyRef:
              key: ONMS_URL
              name: serverless-config