# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: esmaster
$patch: delete

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esmaster
$patch: delete