# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: onms
spec:
  template:
    spec:
      containers:
      - name: onms
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
          $patch: replace
      - name: nfs
        $patch: delete
