# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules
$patch: delete

---
apiVersion: v1
kind: Service
metadata:
  name: ext-kafka
$patch: delete
