# @author Alejandro Galue <agalue@opennms.org>

---
apiVersion: v1
kind: Service
metadata:
  name: opennms-ui
$patch: delete

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onms-ui
$patch: delete